safe: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: bright 
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Tomer Cohen
    # url:  http://example.com/
    company:
        name: Mozilla Israel
        url:  http://mozilla.org.il/

fork_url: https://github.com/MozillaIsrael/Mozilla-Summit-2013-presentation
progress: true

#togetherjs: true
