safe: true
markdown: kramdown
pygments: true
permalink: /:title.html

default_theme: ribbon
default_width: 792
default_lang: en
default_body_class: list

author:
    name: Tomer Cohen
    # url:  http://example.com/
    company:
        name: Mozilla Israel
        # url:  http://example.com/

#fork_url: https://github.com/shower/shower
progress: true
